name: weather
description: A weather app that fetches data from https://www.metaweather.com/api/
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  intl: ^0.17.0
  get: ^4.6.1
  dio: ^4.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true